theme: jekyll-theme-leap-day
# Site settings
title: 本贾名                     #你博客的标题
SEOTitle: 本贾名的yy        #显示在浏览器上搜索的时候显示的标题
header-img: img/伦索伊斯马拉年赛斯国家公园.jpg     #显示在首页的背景图片
email: mac_zhang@126.com    
description: "You Blog"              #网站介绍
keyword: "CV、CNN、计算机视觉、闲聊、小说" #关键词
url: "https://ljczhang.github.io/"          # 这个就是填写你的博客地址
baseurl: ""      # 这个我们不用填写
sidebar: true                           # 是否开启侧边栏.
sidebar-about-description: ""
sidebar-avatar:/img/SE.JPG      # 你的个人头像 这里你可以改成我在img文件夹中的两张备用照片 img/avatar-m 或 avatar-g
